version: '3.9'

services:
  track_count_system_web_socket:
    container_name: track-count-system-web-socket
    image: track-count-system-web-socket
    build:
      context: ./WebSocket
      dockerfile: Dockerfile
    ports:
      - "8009:8009"
    environment:
      - PYTHONUNBUFFERED=1

  track_count_system_rest_api:
    container_name: track-count-system-rest-api
    image: track-count-system-rest-api
    build:
      context: ./RestAPI
      dockerfile: Dockerfile
    ports:
      - "8011:8011"
    environment:
      - PYTHONUNBUFFERED=1